server:
  port: 8080
  servlet:
    context-path: /fanduel-depth-charts

spring:
  datasource:
    url: jdbc:h2:mem:depthcharts;MODE=LEGACY
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console